services:
  postgres-test:
    image: postgres:16-alpine
    container_name: e-mobility-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: e_mobility_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: