services:
  postgres:
    image: postgres:16-alpine
    container_name: e-mobility-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: e_mobility
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: